name: Configuration variable for multiple workflow
on:
  workflow_dispatch
env:
  cloud: aws-cloud

jobs:
  config:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "Say Hello to Ravi...!!"
        run: echo "$Greeting $first_Name is using $cloud with ${{vars.PROJECT_ID}} 
        env:
          first_Name: Raviranjan
    
